title: Rule of the Sun / Правление Солнца
description: Небольшая вики про систему на основе Cairn
theme: just-the-docs

url: https://onthotechnologist.github.io/ruleofthesun
baseurl: "/ruleofthesun"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
